[build]
builder = "nixpacks"

[build.nixpacksPlan]
phases = ["setup", "install", "build"]

[build.nixpacksPlan.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[build.nixpacksPlan.install]
cmds = ["pnpm install --frozen-lockfile"]

[build.nixpacksPlan.build]
cmds = ["pnpm --filter bnb-prayagraj-api build"]

[deploy]
startCommand = "pnpm --filter bnb-prayagraj-api start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"