[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmd = "pnpm install --frozen-lockfile"

[phases.build]
cmd = "pnpm --filter bnb-prayagraj-api build"

[start]
cmd = "pnpm --filter bnb-prayagraj-api start"

[variables]
NIXPACKS_NODE_VERSION = "22"
